
package study.soap.ws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EstoqueWS", targetNamespace = "http://ws.estoque.caelum.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EstoqueWS {


    /**
     * 
     * @param filtros
     * @return
     *     returns java.util.List<study.soap.ws.client.Item>
     */
    @WebMethod(action = "http://ws.estoque.caelum.com.br/EstoqueWS/todosOsItensRequest")
    @WebResult(name = "itens", targetNamespace = "")
    @RequestWrapper(localName = "todosOsItens", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "study.soap.ws.client.TodosOsItens")
    @ResponseWrapper(localName = "todosOsItensResponse", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "study.soap.ws.client.TodosOsItensResponse")
    @Action(input = "http://ws.estoque.caelum.com.br/EstoqueWS/todosOsItensRequest", output = "http://ws.estoque.caelum.com.br/EstoqueWS/todosOsItensResponse")
    public List<Item> todosOsItens(
        @WebParam(name = "filtros", targetNamespace = "")
        Filtros filtros);

    /**
     * 
     * @param parameters
     * @param token
     * @return
     *     returns study.soap.ws.client.CadastrarItemResponse
     * @throws AutotizacaoException
     */
    @WebMethod(action = "http://ws.estoque.caelum.com.br/EstoqueWS/cadastrarItemRequest")
    @WebResult(name = "cadastrarItemResponse", targetNamespace = "http://ws.estoque.caelum.com.br/", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://ws.estoque.caelum.com.br/EstoqueWS/cadastrarItemRequest", output = "http://ws.estoque.caelum.com.br/EstoqueWS/cadastrarItemResponse", fault = {
        @FaultAction(className = AutotizacaoException.class, value = "http://ws.estoque.caelum.com.br/EstoqueWS/cadastrarItem/Fault/AutotizacaoException")
    })
    public CadastrarItemResponse cadastrarItem(
        @WebParam(name = "cadastrarItem", targetNamespace = "http://ws.estoque.caelum.com.br/", partName = "parameters")
        CadastrarItem parameters,
        @WebParam(name = "token", targetNamespace = "http://ws.estoque.caelum.com.br/", header = true, partName = "token")
        TokenUsuario token)
        throws AutotizacaoException
    ;

}
