package br.com.caelum.estoque.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2016-06-13T23:22:20.220-03:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://ws.estoque.caelum.com.br/", name = "EstoqueWS")
@XmlSeeAlso({ObjectFactory.class})
public interface EstoqueWS {

    @WebMethod
    @Action(input = "http://ws.estoque.caelum.com.br/EstoqueWS/todosOsItensRequest", output = "http://ws.estoque.caelum.com.br/EstoqueWS/todosOsItensResponse")
    @RequestWrapper(localName = "todosOsItens", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "br.com.caelum.estoque.ws.TodosOsItens")
    @ResponseWrapper(localName = "todosOsItensResponse", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "br.com.caelum.estoque.ws.TodosOsItensResponse")
    @WebResult(name = "itens", targetNamespace = "")
    public java.util.List<br.com.caelum.estoque.ws.Item> todosOsItens(
        @WebParam(name = "filtros", targetNamespace = "")
        br.com.caelum.estoque.ws.Filtros filtros
    );

    @WebMethod
    @Action(input = "http://ws.estoque.caelum.com.br/EstoqueWS/cadastrarItemRequest", output = "http://ws.estoque.caelum.com.br/EstoqueWS/cadastrarItemResponse", fault = {@FaultAction(className = AutotizacaoException.class, value = "http://ws.estoque.caelum.com.br/EstoqueWS/cadastrarItem/Fault/AutotizacaoException")})
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "cadastrarItemResponse", targetNamespace = "http://ws.estoque.caelum.com.br/", partName = "result")
    public CadastrarItemResponse cadastrarItem(
        @WebParam(partName = "parameters", name = "cadastrarItem", targetNamespace = "http://ws.estoque.caelum.com.br/")
        CadastrarItem parameters,
        @WebParam(partName = "token", name = "token", targetNamespace = "http://ws.estoque.caelum.com.br/", header = true)
        TokenUsuario token
    ) throws AutotizacaoException;
}
